# Generated by Django 6.0.6 on 2026-06-15 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_paymentreceipt_paymentitem_delete_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentitem',
            name='due_amount',
        ),
        migrations.AddField(
            model_name='paymentreceipt',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='paymentreceipt',
            name='due_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
