# Generated by Django 6.0.6 on 2026-06-07 06:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title_en', models.CharField(max_length=255)),
                ('title_bn', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description_en', models.TextField()),
                ('description_bn', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='cms/blogs/')),
                ('author', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title_en', models.CharField(max_length=255)),
                ('title_bn', models.CharField(blank=True, max_length=255, null=True)),
                ('cover_image', models.ImageField(upload_to='cms/events/')),
                ('date_time', models.DateTimeField()),
                ('venue', models.CharField(max_length=255)),
                ('description_en', models.TextField()),
                ('description_bn', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Upcoming', 'Upcoming'), ('Past', 'Past')], default='Upcoming', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('registration_link', models.URLField(blank=True, help_text='External registration URL for upcoming events', null=True)),
            ],
            options={
                'ordering': ['-date_time'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_en', models.CharField(max_length=255)),
                ('question_bn', models.CharField(blank=True, max_length=255, null=True)),
                ('answer_en', models.TextField()),
                ('answer_bn', models.TextField(blank=True, null=True)),
                ('category', models.CharField(default='General', help_text='e.g. Admissions, Academic, General', max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='cms/hero_slides/')),
                ('title_en', models.CharField(max_length=255)),
                ('title_bn', models.CharField(blank=True, max_length=255, null=True)),
                ('subtitle_en', models.TextField()),
                ('subtitle_bn', models.TextField(blank=True, null=True)),
                ('cta_button_1_text', models.CharField(blank=True, default='Learn More', max_length=50)),
                ('cta_button_1_link', models.CharField(blank=True, default='/about-us', max_length=200)),
                ('cta_button_2_text', models.CharField(blank=True, default='Admission Info', max_length=50)),
                ('cta_button_2_link', models.CharField(blank=True, default='/admissions', max_length=200)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in which slides appear')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title_en', models.CharField(max_length=255)),
                ('title_bn', models.CharField(blank=True, max_length=255, null=True)),
                ('description_en', models.TextField()),
                ('description_bn', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('Academic', 'Academic'), ('Administrative', 'Administrative'), ('Exam', 'Exam'), ('Event', 'Event'), ('General', 'General')], max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='cms/notices/pdfs/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='events/gallery/')),
                ('caption_en', models.CharField(blank=True, help_text='English caption', max_length=255)),
                ('caption_bn', models.CharField(blank=True, help_text='Bengali caption', max_length=255)),
                ('order', models.PositiveIntegerField(default=0, help_text='Sort order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='cms.event')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('message', models.TextField(blank=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='cms.event')),
            ],
        ),
    ]
