# Generated by Django 6.0.6 on 2026-06-21 18:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staffs', '0001_initial'),
        ('teachers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employee_type', models.CharField(choices=[('TEACHER', 'Teacher'), ('STAFF', 'Staff')], max_length=20)),
                ('bank_account_name', models.CharField(max_length=150)),
                ('bank_account_number', models.CharField(max_length=50)),
                ('routing_number', models.CharField(max_length=50)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('branch_name', models.CharField(blank=True, max_length=100, null=True)),
                ('basic_salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('house_rent', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('medical_allowance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('transport_allowance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('other_allowance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('provident_fund_pct', models.DecimalField(decimal_places=2, default=0.0, help_text='PF deduction percentage (e.g., 10 for 10%)', max_digits=5)),
                ('tax_pct', models.DecimalField(decimal_places=2, default=0.0, help_text='Tax deduction percentage', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payroll_profile', to='staffs.staff')),
                ('teacher', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payroll_profile', to='teachers.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='PayrollAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Late', 'Late'), ('Half-Day', 'Half-Day')], default='Present', max_length=15)),
                ('check_in_time', models.TimeField(blank=True, null=True)),
                ('check_out_time', models.TimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='payroll.payrollprofile')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='MonthlySalary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('basic_salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('house_rent', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('medical_allowance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('transport_allowance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('other_allowance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('bonus', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('provident_fund_deduction', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('tax_deduction', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('loan_deduction', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('unpaid_leave_deduction', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('other_deduction', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('net_payable', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('payment_status', models.CharField(choices=[('Unpaid', 'Unpaid'), ('Paid', 'Paid')], default='Unpaid', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salaries', to='payroll.payrollprofile')),
            ],
            options={
                'ordering': ['-year', '-month'],
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_date', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monthly_emi', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remaining_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purpose', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='False when fully repaid')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='payroll.payrollprofile')),
            ],
            options={
                'ordering': ['-loan_date'],
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('Casual', 'Casual Leave'), ('Sick', 'Sick Leave'), ('Earned', 'Earned Leave'), ('Maternity', 'Maternity Leave'), ('Paternity', 'Paternity Leave'), ('Unpaid', 'Leave Without Pay')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='payroll.payrollprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='payrollprofile',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('employee_type', 'TEACHER'), ('staff__isnull', True), ('teacher__isnull', False)), models.Q(('employee_type', 'STAFF'), ('staff__isnull', False), ('teacher__isnull', True)), _connector='OR'), name='payroll_employee_type_match'),
        ),
        migrations.AlterUniqueTogether(
            name='payrollattendance',
            unique_together={('employee', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='monthlysalary',
            unique_together={('employee', 'month', 'year')},
        ),
    ]
